# **1. Import Library**

In [28]:
#Pandas digunakan untuk membaca, mengolah, dan menampilkan data, seperti data dari file Excel.
import pandas as pd

Digunakan untuk memanggil library pandas, yaitu library Python yang dipakai untuk mengolah dan menganalisis data, misalnya dari file Excel atau CSV.

In [29]:
# Langkah 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

from google.colab import drive dan drive.mount('/content/drive') berfungsi untuk menghubungkan Google Colab dengan Google Drive, di mana langkah pertama mengimpor modul drive agar bisa digunakan, dan langkah kedua melakukan proses mounting sehingga Colab mendapat akses membaca dan menulis file di Google Drive setelah pengguna memberikan otorisasi.

## **2. Baca Dataset Pemain Sepak Bola yang Kotor**

In [30]:
# Baca file .xlsx
file_path = '/content/drive/MyDrive/Colab Notebooks/DATA MENTAH PEMAIN SEPAK BOLA.xlsx'
data = pd.read_excel(file_path, engine='openpyxl')  # Gunakan openpyxl untuk file .xlsx

Kode tersebut berfungsi untuk membaca file Excel (.xlsx) yang ada di Google Drive ke dalam Python, di mana file_path menyimpan lokasi file, lalu pd.read_excel(file_path, engine='openpyxl') digunakan untuk membuka file tersebut dengan bantuan engine openpyxl, dan hasilnya disimpan ke variabel data dalam bentuk DataFrame sehingga bisa langsung diolah dengan pandas.

In [31]:
# Tampilkan data
print(data)

   ID_Pemain      Nama_Pemain      Usia Jenis_Kelamin     Posisi  \
0   PM-00001     Tirsa Adrian     21 th     Laki-laki  Penyerang
1   PM-00002     Budi Santoso        23     Laki-laki  Gelandang
2   PM-00003    Candra Wijaya  25 tahun     Laki-laki        bek
3   PM-00004    Dimas Saputra      20th     Laki-laki  Penyerang
4   PM-00005     Eko Ramadhan  27 tahun     Laki-laki      Kiper
5   PM-00006    Fajar Hidayat        22     Laki laki  Gelandang
6   PM-00007     Galang Putra    24 thn     Laki-laki        Bek
7   PM-00008    Hendra Wijaya        29     Laki-laki  Penyerang
8   PM-00009      Ilham Fauzi  21 tahun     Laki-laki  Gelandang
9   PM-00010     Joko Susanto      26th     Laki-laki        Bek
10  PM-00011    Kevin Maulana        22     Laki-laki  penyerang
11  PM-00012     Lukman Hakim  28 tahun     Laki-laki  Gelandang
12  PM-00013          M Rizky     23 th     Laki-laki        Bek
13  PM-00014    Nanda Saputra        24     Laki-laki  Penyerang
14  PM-00015   Oki Firmansyah  30 tahun     Laki-laki      Kiper
15  PM-00016   Putra Ramadhan        20     Laki laki  Gelandang
16  PM-00017   Rian Kurniawan    25 thn     Laki-laki        Bek
17  PM-00018     Sandi Irawan        27     Laki-laki  Penyerang
18  PM-00019   Taufik Hidayat  22 tahun     Laki-laki  Gelandang
19  PM-00020     Ubay Prakoso     29 th     Laki-laki        bek
20  PM-00021     Vino Saputra        23     Laki-laki  Penyerang
21  PM-00022   Wahyu Setiawan  26 tahun     Laki-laki  Gelandang
22  PM-00023     Yogi Pratama      21th     Laki-laki        Bek
23  PM-00024  Zaki Firmansyah        28     Laki-laki      Kiper
24  PM-00025   Aldi Kurniawan  25 tahun     Laki-laki  Penyerang
25  PM-00026   Bagas Setiawan        24     Laki-laki  Gelandang
26  PM-00027     Cakra Wijaya    27 thn     Laki-laki        Bek
27  PM-00028     Deni Saputra  30 tahun     Laki-laki  Penyerang
28  PM-00029    Erwin Maulana        23     Laki-laki  Gelandang
29  PM-00030     Farhan Akbar     22 th     Laki-laki        Bek

             Klub Kaki_Dominan Penampilan Gol Assist Menit_Bermain  \
0        Arema FC        kanan        150  60     40    2100 menit
1         Persija        Kanan        28x   6      9          2240
2       Persebaya        KANAN         25   2      3      2100 mnt
3          Persib         Kiri         19   9      4          1430
4        Arema FC        kanan         30   -      -    2700 menit
5      PSS Sleman         kiri         16   3      6          1200
6     Bali United        Kanan    27 kali   1      2    2310 menit
7     Persis Solo        KANAN         21   7      3          1580
8        Arema FC         Kiri         13   2      4       980 mnt
9   Madura United        kanan         29   3      1          2500
10        Persita        Kanan  23x/musim  10      7    1740 menit
11  Barito Putera         kiri         18   4      5          1390
12         Persik        kanan         26   2      2      2180 mnt
13      Borneo FC        Kanan         27  13      6    2100 menit
14        Persija        Kanan         20   0      0          1800
15       Arema FC        kanan        12x   1      3     850 menit
16         Persib         KIRI         30   3      4          2650
17      Persebaya        Kanan    26 kali   8      5      1980 mnt
18   PSM Makassar        kanan         15   2      2          1100
19    Bali United        Kanan         24   1      3    2050 menit
20        Persita         kiri         22  11      8          1690
21     PSS Sleman        KANAN        20x   5      7      1550 mnt
22       Arema FC        Kanan         10   0      1     720 menit
23    Persis Solo        kanan    31 kali   0      0          2790
24         Persik         KIRI         25   9      5      1900 mnt
25   PSM Makassar        Kanan         14   3      4    1050 menit
26  Madura United        kanan        28x   2      1          2420
27  Barito Putera        Kanan         17   5      2      1260 mnt
28      Borneo FC         Kiri    29 kali   7     10    2380 menit
29      Persebaya        kanan         18   1      2          1340

    Kartu_Kuning       Status
0              2        Aktif
1              4        aktif
2              6        Aktif
3              1        aktif
4              3        Aktif
5              2  Tidak aktif
6              7        Aktif
7              5        aktif
8              1  Tidak Aktif
9              8        Aktif
10             2        Aktif
11             5  Tidak aktif
12             6        AKTIF
13             3        Aktif
14             2  Tidak Aktif
15             1  tidak aktif
16             9        Aktif
17             4        aktif
18             3  Tidak Aktif
19             7        Aktif
20             2        Aktif
21             4        Aktif
22             2  Tidak aktif
23             4        Aktif
24             3        Aktif
25             2  Tidak Aktif
26            10        Aktif
27             6  Tidak aktif
28             5        AKTIF
29             4        Aktif

### **3. Menampilkan struktur variabel data Pemain**

In [32]:
print("Struktur Data Pemain:")
print(data.info())

Struktur Data Pemain:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Pemain      30 non-null     object
 1   Nama_Pemain    30 non-null     object
 2   Usia           30 non-null     object
 3   Jenis_Kelamin  30 non-null     object
 4   Posisi         30 non-null     object
 5   Klub           30 non-null     object
 6   Kaki_Dominan   30 non-null     object
 7   Penampilan     30 non-null     object
 8   Gol            30 non-null     object
 9   Assist         30 non-null     object
 10  Menit_Bermain  30 non-null     object
 11  Kartu_Kuning   30 non-null     int64
 12  Status         30 non-null     object
dtypes: int64(1), object(12)
memory usage: 3.2+ KB
None

Kode tersebut berfungsi untuk menampilkan struktur DataFrame data, yaitu dengan mencetak teks "Struktur Data Pemain:" lalu menampilkan informasi jumlah baris, kolom, nama kolom, tipe data, serta jumlah nilai non-null dari setiap kolom menggunakan data.info().

In [33]:
# Tampilkan nama kolom dan tipe data kolom
column_types = data.dtypes
print(column_types)

ID_Pemain        object
Nama_Pemain      object
Usia             object
Jenis_Kelamin    object
Posisi           object
Klub             object
Kaki_Dominan     object
Penampilan       object
Gol              object
Assist           object
Menit_Bermain    object
Kartu_Kuning      int64
Status           object
dtype: object

## **4. Data Cleansing-Standarisasi kolom ID_Pemain**

In [34]:
# Function to format 'ID Pemain'
def format_ID_Pemain(ID):
    if ID.startswith("PM-") and len(ID.split('-')[-1]) == 4:
        return ID[:3] + '0' + ID[3:]  # Add an extra '0' after "ID-"
    return ID

Program tersebut digunakan untuk menyeragamkan format data pada kolom ID_Pemain agar memiliki format ID yang konsisten. Fungsi format_ID_Pemain(ID) digunakan untuk memeriksa setiap ID pemain. Perintah startswith("PM-") digunakan untuk memastikan ID diawali dengan PM-, sedangkan len(ID.split('-')[-1]) == 4 digunakan untuk memeriksa apakah angka setelah tanda - terdiri dari 4 digit. Jika kedua kondisi terpenuhi, ID[:3] + 0 + ID[3:] digunakan untuk menambahkan angka 0 setelah PM-, misalnya PM-1234 menjadi PM-01234. Jika kondisi tidak terpenuhi, return ID mengembalikan ID tanpa perubahan. Selanjutnya, apply(format_ID_Pemain) menerapkan fungsi tersebut ke seluruh data pada kolom ID_Pemain.

In [35]:
# Apply the function to the 'ID_Pemain' column
data['ID_Pemain'] = data['ID_Pemain'].apply(format_ID_Pemain)

Perintah tersebut digunakan untuk menerapkan fungsi format_ID_Pemain pada seluruh data yang terdapat di kolom ID_Pemain. Bagian data['ID_Pemain'] digunakan untuk memilih kolom ID_Pemain, kemudian apply(format_ID_Pemain) menjalankan fungsi format_ID_Pemain pada setiap nilai ID. Hasil dari proses tersebut kemudian disimpan kembali ke kolom ID_Pemain, sehingga setiap ID pemain yang belum sesuai format akan diperbaiki sesuai aturan yang telah dibuat.

In [36]:
# Display the updated 'ID_Pemain' column
data[['ID_Pemain']].head()

  ID_Pemain
0  PM-00001
1  PM-00002
2  PM-00003
3  PM-00004
4  PM-00005

### **5. Data Cleansing-Standarisasi kolom Nama_Pemain**

In [37]:
# Function to clean 'Nama_Pemain'
def clean_name(name):
    name = str(name).strip() #Menghilangkan spasi di awal dan akhir.
    name = ' '.join(name.split()) #Menghilangkan spasi berlebihan.
    return name.title()

# Apply the cleaning function
data['Nama_Pemain'] = data['Nama_Pemain'].apply(clean_name)

# Display the cleaned data
data[['Nama_Pemain']].head()

     Nama_Pemain
0   Tirsa Adrian
1   Budi Santoso
2  Candra Wijaya
3  Dimas Saputra
4   Eko Ramadhan

Program tersebut digunakan untuk membersihkan dan menyeragamkan data pada kolom Nama_Pemain. Fungsi clean_name(name) digunakan untuk membersihkan setiap nama pemain. Perintah str(name) mengubah data menjadi teks, sedangkan strip() digunakan untuk menghilangkan spasi di awal dan akhir nama. Perintah split() dan join() digunakan untuk menghilangkan spasi berlebihan di antara kata. Kemudian title() digunakan untuk membuat huruf awal setiap kata menjadi huruf kapital. Selanjutnya, apply(clean_name) menerapkan fungsi tersebut ke seluruh data pada kolom Nama_Pemain. Terakhir, data[['Nama_Pemain']].head() digunakan untuk menampilkan 5 data pertama setelah proses pembersihan.

## **6. Data Cleansing-Standarisasi Kolom Usia**

In [38]:
# Function to standardize 'Usia'
def standardize_age(age):
    age = str(age)
    age = age.replace('tahun', '')
    age = age.replace('thn', '')
    age = age.replace('th', '')
    age = age.replace(' ', '')
    return int(age)

# Apply the standardization function
data['Usia'] = data['Usia'].apply(standardize_age)

# Display the standardized age
data[['Usia']].head()

   Usia
0    21
1    23
2    25
3    20
4    27

Program tersebut digunakan untuk menyeragamkan format data pada kolom Usia agar seluruh data usia menjadi angka. Fungsi standardize_age(age) digunakan untuk membersihkan data usia dengan mengubahnya menjadi teks menggunakan str(age). Perintah replace('tahun', ''), replace('thn', ''), dan replace('th', '') digunakan untuk menghapus berbagai bentuk satuan usia. Selanjutnya, replace(' ', '') digunakan untuk menghilangkan spasi pada data. Perintah int(age) mengubah hasilnya menjadi bilangan bulat, misalnya 21 tahun menjadi 21. Kemudian apply(standardize_age) menerapkan fungsi tersebut ke seluruh data pada kolom Usia. Terakhir, data[['Usia']].head() digunakan untuk menampilkan 5 data pertama setelah proses standardisasi.

## **7. Data Cleansing Standarisasi kolom Jenis_Kelamin**

In [39]:
# Standardize 'Jenis_Kelamin'
data['Jenis_Kelamin'] = data['Jenis_Kelamin'].replace({
    'Laki laki': 'Laki-laki'
})

# Display the standardized data
data[['Jenis_Kelamin']].head()

  Jenis_Kelamin
0     Laki-laki
1     Laki-laki
2     Laki-laki
3     Laki-laki
4     Laki-laki

Program tersebut digunakan untuk menyeragamkan data pada kolom Jenis_Kelamin. Perintah replace() digunakan untuk mengganti penulisan Laki laki menjadi Laki-laki agar format penulisan data menjadi konsisten. Selanjutnya, hasil perubahan disimpan kembali ke kolom Jenis_Kelamin. Terakhir, data[['Jenis_Kelamin']].head() digunakan untuk menampilkan 5 data pertama setelah proses standardisasi.

## **8. Data Cleansing Standarisasi kolom Posisi**

In [40]:
# Standardize 'Posisi'
data['Posisi'] = data['Posisi'].str.title()

# Display the standardized data
data[['Posisi']].head()

      Posisi
0  Penyerang
1  Gelandang
2        Bek
3  Penyerang
4      Kiper

Program tersebut digunakan untuk menyeragamkan penulisan data pada kolom Posisi. Perintah data['Posisi'] digunakan untuk memilih kolom Posisi, kemudian str.title() digunakan untuk mengubah huruf awal setiap kata menjadi huruf kapital. Dengan demikian, data seperti bek akan menjadi Bek dan penyerang menjadi Penyerang. Selanjutnya, hasil standardisasi disimpan kembali ke kolom Posisi. Terakhir, data[['Posisi']].head() digunakan untuk menampilkan 5 data pertama setelah proses standardisasi.

# **9. Data Cleansing Standarisasi kolom Kaki_Dominan**

In [41]:
# Standardize 'Kaki_Dominan'
data['Kaki_Dominan'] = data['Kaki_Dominan'].str.title()

# Display the standardized data
data[['Kaki_Dominan']].head()

  Kaki_Dominan
0        Kanan
1        Kanan
2        Kanan
3         Kiri
4        Kanan

Program tersebut digunakan untuk menyeragamkan penulisan data pada kolom Kaki_Dominan. Perintah data['Kaki_Dominan'] digunakan untuk memilih kolom Kaki_Dominan, kemudian str.title() digunakan untuk membuat huruf awal menjadi huruf kapital. Dengan demikian, data seperti kanan, KANAN, atau Kanan akan diseragamkan menjadi Kanan, begitu juga kiri, KIRI, atau Kiri akan menjadi Kiri. Selanjutnya, hasil standardisasi disimpan kembali ke kolom Kaki_Dominan. Terakhir, data[['Kaki_Dominan']].head() digunakan untuk menampilkan 5 data pertama setelah proses standardisasi.

## **10. Data Cleansing Standarisasi kolom Penampilan**

In [42]:
# Function to standardize 'Penampilan'
def standardize_penampilan(appearance):
    appearance = str(appearance)
    appearance = appearance.replace('x/musim', '')
    appearance = appearance.replace('kali', '')
    appearance = appearance.replace('x', '')
    appearance = appearance.strip()
    return int(appearance)

# Apply the standardization function
data['Penampilan'] = data['Penampilan'].apply(standardize_penampilan)

# Display the standardized data
data[['Penampilan']].head()

   Penampilan
0         150
1          28
2          25
3          19
4          30

Program tersebut digunakan untuk menyeragamkan format data pada kolom Penampilan agar seluruh data penampilan menjadi angka. Fungsi standardize_penampilan(appearance) digunakan untuk membersihkan data penampilan dengan mengubahnya menjadi teks menggunakan str(appearance). Perintah replace('x/musim', ''), replace('kali', ''), dan replace('x', '') digunakan untuk menghapus satuan atau keterangan yang terdapat pada data, seperti 23x, 27 kali, atau 23x/musim. Selanjutnya, strip() digunakan untuk menghilangkan spasi di awal dan akhir data. Perintah int(appearance) mengubah hasilnya menjadi bilangan bulat. Kemudian apply(standardize_penampilan) menerapkan fungsi tersebut ke seluruh data pada kolom Penampilan. Terakhir, data[['Penampilan']].head() digunakan untuk menampilkan 5 data pertama setelah proses standardisasi.

# **11. Data Cleansing Standarisasi kolom Gol**

In [43]:
# Replace '-' with 0 in 'Gol'
data['Gol'] = data['Gol'].replace('-', 0)

# Convert to integer
data['Gol'] = data['Gol'].astype(int)

# Display the cleaned data
data[['Gol']].head()

/tmp/ipykernel_2507/2519236735.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Gol'] = data['Gol'].replace('-', 0)

   Gol
0   60
1    6
2    2
3    9
4    0

Program tersebut digunakan untuk membersihkan data pada kolom Gol agar seluruh nilai memiliki format angka. Perintah replace('-', 0) digunakan untuk mengganti tanda - yang terdapat pada data Gol menjadi angka 0, yang menunjukkan bahwa pemain tersebut tidak memiliki gol. Selanjutnya, astype(int) digunakan untuk mengubah seluruh data pada kolom Gol menjadi bilangan bulat. Terakhir, data[['Gol']].head() digunakan untuk menampilkan 5 data pertama setelah proses pembersihan.

# **12. Data Cleansing Standarisasi kolom Assist**

In [44]:
# Replace '-' with 0 in 'Assist'
data['Assist'] = data['Assist'].replace('-', 0)

# Convert to integer
data['Assist'] = data['Assist'].astype(int)

# Display the cleaned data
data[['Assist']].head()

/tmp/ipykernel_2507/3333946724.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Assist'] = data['Assist'].replace('-', 0)

   Assist
0      40
1       9
2       3
3       4
4       0

Program tersebut digunakan untuk membersihkan data pada kolom Assist agar seluruh nilai memiliki format angka. Perintah replace('-', 0) digunakan untuk mengganti tanda - yang terdapat pada data Assist menjadi angka 0, yang menunjukkan bahwa pemain tersebut tidak memiliki assist. Selanjutnya, astype(int) digunakan untuk mengubah seluruh data pada kolom Assist menjadi bilangan bulat. Terakhir, data[['Assist']].head() digunakan untuk menampilkan 5 data pertama setelah proses pembersihan.

# **13. Data Cleansing Standarisasi kolom Menit_Bermain**

In [45]:
# Function to standardize 'Menit_Bermain'
def standardize_menit(minute):
    minute = str(minute)
    minute = minute.replace('menit', '')
    minute = minute.replace('mnt', '')
    minute = minute.strip()
    return int(minute)

# Apply the standardization function
data['Menit_Bermain'] = data['Menit_Bermain'].apply(standardize_menit)

# Display the standardized data
data[['Menit_Bermain']].head()

   Menit_Bermain
0           2100
1           2240
2           2100
3           1430
4           2700

Program tersebut digunakan untuk menyeragamkan format data pada kolom Menit_Bermain agar seluruh data waktu bermain menjadi angka. Fungsi standardize_menit(minute) digunakan untuk membersihkan data dengan mengubahnya menjadi teks menggunakan str(minute). Perintah replace('menit', '') dan replace('mnt', '') digunakan untuk menghapus satuan menit yang terdapat pada data. Selanjutnya, strip() digunakan untuk menghilangkan spasi di awal dan akhir data. Perintah int(minute) mengubah hasilnya menjadi bilangan bulat. Kemudian apply(standardize_menit) menerapkan fungsi tersebut ke seluruh data pada kolom Menit_Bermain. Terakhir, data[['Menit_Bermain']].head() digunakan untuk menampilkan 5 data pertama setelah proses standardisasi.

# **14. Data Cleansing Standarisasi kolom Status**

In [46]:
# Standardize 'Status'
data['Status'] = data['Status'].str.title()

# Display the standardized data
data[['Status']].head()

  Status
0  Aktif
1  Aktif
2  Aktif
3  Aktif
4  Aktif

Program tersebut digunakan untuk menyeragamkan penulisan data pada kolom Status dengan mengubah huruf pertama setiap kata menjadi huruf kapital menggunakan .str.title(). Setelah itu, data[['Status']].head() digunakan untuk menampilkan 5 data pertama dari kolom Status sebagai hasil pengecekan.

# **15. Data Cleansing-Deduplikasi Data**

In [47]:
# Check duplicate data
duplicate_data = data[data.duplicated(keep=False)]

print("Data Duplikat:")
print(duplicate_data)

Data Duplikat:
Empty DataFrame
Columns: [ID_Pemain, Nama_Pemain, Usia, Jenis_Kelamin, Posisi, Klub, Kaki_Dominan, Penampilan, Gol, Assist, Menit_Bermain, Kartu_Kuning, Status]
Index: []

Program tersebut digunakan untuk memeriksa data yang duplikat atau memiliki isi yang sama. Fungsi duplicated(keep=False) akan mencari semua baris yang memiliki data sama, kemudian hasilnya disimpan dalam duplicate_data. Selanjutnya, print() digunakan untuk menampilkan data duplikat yang ditemukan.

In [48]:
# Count duplicate data
print("Jumlah data duplikat:", data.duplicated().sum())

Jumlah data duplikat: 0

# **16. Data Enrichment**

In [49]:
# Check missing values
missing_values = data.isna().sum()

print("Jumlah Missing Value:")
print(missing_values)

Jumlah Missing Value:
ID_Pemain        0
Nama_Pemain      0
Usia             0
Jenis_Kelamin    0
Posisi           0
Klub             0
Kaki_Dominan     0
Penampilan       0
Gol              0
Assist           0
Menit_Bermain    0
Kartu_Kuning     0
Status           0
dtype: int64

Program tersebut digunakan untuk memeriksa data yang kosong atau missing value pada setiap kolom. Fungsi isna().sum() menghitung jumlah data kosong pada masing-masing kolom, kemudian hasilnya disimpan dalam missing_values dan ditampilkan menggunakan print().

# **17. Tampilan hasil cleansing**

In [50]:
# Display cleaned dataset
print("Data Setelah Cleansing:")
print(data)

Data Setelah Cleansing:
   ID_Pemain      Nama_Pemain  Usia Jenis_Kelamin     Posisi           Klub  \
0   PM-00001     Tirsa Adrian    21     Laki-laki  Penyerang       Arema FC
1   PM-00002     Budi Santoso    23     Laki-laki  Gelandang        Persija
2   PM-00003    Candra Wijaya    25     Laki-laki        Bek      Persebaya
3   PM-00004    Dimas Saputra    20     Laki-laki  Penyerang         Persib
4   PM-00005     Eko Ramadhan    27     Laki-laki      Kiper       Arema FC
5   PM-00006    Fajar Hidayat    22     Laki-laki  Gelandang     PSS Sleman
6   PM-00007     Galang Putra    24     Laki-laki        Bek    Bali United
7   PM-00008    Hendra Wijaya    29     Laki-laki  Penyerang    Persis Solo
8   PM-00009      Ilham Fauzi    21     Laki-laki  Gelandang       Arema FC
9   PM-00010     Joko Susanto    26     Laki-laki        Bek  Madura United
10  PM-00011    Kevin Maulana    22     Laki-laki  Penyerang        Persita
11  PM-00012     Lukman Hakim    28     Laki-laki  Gelandang  Barito Putera
12  PM-00013          M Rizky    23     Laki-laki        Bek         Persik
13  PM-00014    Nanda Saputra    24     Laki-laki  Penyerang      Borneo FC
14  PM-00015   Oki Firmansyah    30     Laki-laki      Kiper        Persija
15  PM-00016   Putra Ramadhan    20     Laki-laki  Gelandang       Arema FC
16  PM-00017   Rian Kurniawan    25     Laki-laki        Bek         Persib
17  PM-00018     Sandi Irawan    27     Laki-laki  Penyerang      Persebaya
18  PM-00019   Taufik Hidayat    22     Laki-laki  Gelandang   PSM Makassar
19  PM-00020     Ubay Prakoso    29     Laki-laki        Bek    Bali United
20  PM-00021     Vino Saputra    23     Laki-laki  Penyerang        Persita
21  PM-00022   Wahyu Setiawan    26     Laki-laki  Gelandang     PSS Sleman
22  PM-00023     Yogi Pratama    21     Laki-laki        Bek       Arema FC
23  PM-00024  Zaki Firmansyah    28     Laki-laki      Kiper    Persis Solo
24  PM-00025   Aldi Kurniawan    25     Laki-laki  Penyerang         Persik
25  PM-00026   Bagas Setiawan    24     Laki-laki  Gelandang   PSM Makassar
26  PM-00027     Cakra Wijaya    27     Laki-laki        Bek  Madura United
27  PM-00028     Deni Saputra    30     Laki-laki  Penyerang  Barito Putera
28  PM-00029    Erwin Maulana    23     Laki-laki  Gelandang      Borneo FC
29  PM-00030     Farhan Akbar    22     Laki-laki        Bek      Persebaya

   Kaki_Dominan  Penampilan  Gol  Assist  Menit_Bermain  Kartu_Kuning  \
0         Kanan         150   60      40           2100             2
1         Kanan          28    6       9           2240             4
2         Kanan          25    2       3           2100             6
3          Kiri          19    9       4           1430             1
4         Kanan          30    0       0           2700             3
5          Kiri          16    3       6           1200             2
6         Kanan          27    1       2           2310             7
7         Kanan          21    7       3           1580             5
8          Kiri          13    2       4            980             1
9         Kanan          29    3       1           2500             8
10        Kanan          23   10       7           1740             2
11         Kiri          18    4       5           1390             5
12        Kanan          26    2       2           2180             6
13        Kanan          27   13       6           2100             3
14        Kanan          20    0       0           1800             2
15        Kanan          12    1       3            850             1
16         Kiri          30    3       4           2650             9
17        Kanan          26    8       5           1980             4
18        Kanan          15    2       2           1100             3
19        Kanan          24    1       3           2050             7
20         Kiri          22   11       8           1690             2
21        Kanan          20    5       7           1550             4
22        Kanan          10    0       1            720             2
23        Kanan          31    0       0           2790             4
24         Kiri          25    9       5           1900             3
25        Kanan          14    3       4           1050             2
26        Kanan          28    2       1           2420            10
27        Kanan          17    5       2           1260             6
28         Kiri          29    7      10           2380             5
29        Kanan          18    1       2           1340             4

         Status
0         Aktif
1         Aktif
2         Aktif
3         Aktif
4         Aktif
5   Tidak Aktif
6         Aktif
7         Aktif
8   Tidak Aktif
9         Aktif
10        Aktif
11  Tidak Aktif
12        Aktif
13        Aktif
14  Tidak Aktif
15  Tidak Aktif
16        Aktif
17        Aktif
18  Tidak Aktif
19        Aktif
20        Aktif
21        Aktif
22  Tidak Aktif
23        Aktif
24        Aktif
25  Tidak Aktif
26        Aktif
27  Tidak Aktif
28        Aktif
29        Aktif

In [51]:
print("Struktur Data Setelah Cleansing:")
data.info()

Struktur Data Setelah Cleansing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Pemain      30 non-null     object
 1   Nama_Pemain    30 non-null     object
 2   Usia           30 non-null     int64
 3   Jenis_Kelamin  30 non-null     object
 4   Posisi         30 non-null     object
 5   Klub           30 non-null     object
 6   Kaki_Dominan   30 non-null     object
 7   Penampilan     30 non-null     int64
 8   Gol            30 non-null     int64
 9   Assist         30 non-null     int64
 10  Menit_Bermain  30 non-null     int64
 11  Kartu_Kuning   30 non-null     int64
 12  Status         30 non-null     object
dtypes: int64(6), object(7)
memory usage: 3.2+ KB

Program tersebut digunakan untuk menampilkan dataset setelah proses cleansing selesai. Fungsi print(data) menampilkan seluruh data yang sudah dibersihkan, sedangkan data.info() digunakan untuk melihat struktur data seperti jumlah baris, kolom, tipe data, dan jumlah data yang terisi pada setiap kolom.

# **18. Download Data hasil cleansing dalam bentuk xlsx**

In [ ]:
# Menyimpan data hasil cleansing ke file Excel
output_path = '/content/DATA PEMAIN SEPAK BOLA HASIL CLEANSING.xlsx'

data.to_excel(output_path, index=False)

print("Data hasil cleansing berhasil disimpan.")

Data hasil cleansing berhasil disimpan.

In [ ]:
from google.colab import files

files.download(output_path)

Program tersebut digunakan untuk menyimpan data hasil cleansing ke dalam file Excel. Fungsi data.to_excel() menyimpan dataset ke file dengan nama DATA PEMAIN SEPAK BOLA HASIL CLEANSING.xlsx, kemudian files.download() digunakan untuk mengunduh file tersebut dari Google Colab ke perangkat.